[package]
distribution = "2201.13.0"
org = "ballerinax"
name = "gitlab"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Vendor/GitLab", "Area/Developer Tools", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-gitlab"

[build-options]
observabilityIncluded = true
